### ISSUE TITLE
More idiomatic slf4j / logback usage

### ISSUE THREAD

**Issue by jmini** [mmornati/springboot-osgi-sample#12]
I really like your project because it helps to understand how OSGi can be used with Spring Boot.

One point I am not really understanding is your decision about slf4j and logback:

You are including following jar into each bundle (`sample-bundle`, `sample-bundle-scr`):

* `slf4j-api-1.7.30.jar`
* `logback-classic-1.2.3.jar`
* `logback-core-1.2.3.jar`

With the corresponding `Bundle-ClassPath` entry in the `MANIFEST.MF`

<img width="938" alt="sample-bundle-scr content" src="https://user-images.githubusercontent.com/1222165/107321326-9ca16080-6aa2-11eb-8123-7221e0635f1e.png">

I am not a Spring or OSGi expert, but I have the feeling it would be better to have an additional entry:
 `org.slf4j;version="[1.7,2)"` in the `Import-Package` directive. The Spring app already contains the slf4j jar. This should be exposed to the OSGi runtime.

**Comment by mmornati** [comment]
Yes I'm pretty sure is not good, but it doesn't Peking in the right way. I did not find the right way with export/import to let it working correctly.
We tested a thing weeks ago exporting all the packages from the core. It seems working but in the end it was not.

Actually in each bundle you don't need to use the same logging system (you don't even have to log).
I tested and in this way I'm able to force each bundle to log in a specific "file". It can fix another problem we have on our side for production 😂

But I'm agree, the best thing to do is keeping bundles with the essentials libs.
